-- (Q1)What is the total revenue generated by male vs female customers?
SELECT gender, SUM (purchase_amount) AS revenue
FROM customer
GROUP BY gender;
-- (Q2)Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT  AVG(purchase_amount) FROM customer)
;
-- (Q3) Which are the top 5 products with highest average revenue ratings?
SELECT item_purchased , ROUND(AVG(review_rating::numeric),2) AS average_revenue_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_revenue_rating DESC
LIMIT 5;
-- (Q4) Compare the average purchase amounts between Standard and Express Shipping?
SELECT shipping_type,
ROUND(AVG(purchase_amount::numeric),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;
-- (Q5) Do subricised customer spend more ? Compare average and total revenge 
-- Between subcribers and non - subcirbers
SELECT subscription_status ,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchase_amount::numeric),2) AS avg_spend,
ROUND(SUM(purchase_amount::numeric),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend;
-- (Q6) Which 5 product have the highest percentage of purchases with discount applied?

SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- (Q7) Segment customer into New, Returning and loyal based, on thier total
-- number of previous purchases and show the count of each segment 
WITH customer_type AS (
	SELECT customer_id, previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'royal'
		END AS customer_segment
	FROM customer
)

SELECT customer_segment, count(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- What are the top three most purchased products within each category?
WITH items_count AS (
	SELECT 
		category,
		item_purchased,
		COUNT(customer_id) AS total_order,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY category, item_purchased
)
SELECT 
	item_rank,
	category,
	item_purchased,
	total_order
FROM items_count
WHERE item_rank <= 3;

-- (Q9)Are customers who are repeat buyers (more than five previous purchases ) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeated_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;
-- (10) What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue 
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
